accepted = [
    "Apache-2.0",
    "MIT",
    "EUPL-1.2",
    "MPL-2.0",
    "Zlib",
    "BSD-3-Clause",
    "0BSD",
    "BSL-1.0",
    "OFL-1.1",
    "Apache-2.0 WITH LLVM-exception",
    "ISC",
    "Unicode-3.0",
    "CC0-1.0",
    "Ubuntu-font-1.0",
    "CDLA-Permissive-2.0",
    "OpenSSL"
]
