open = ["Ctrl+O"]
undo = ["Ctrl+Z", "U"]
redo = ["Ctrl+Shift+Z", "Ctrl+Y"]
toggle_side_panel = ["B"]
toggle_toolbar = ["T"]
goto_end = ["E"]
goto_start = ["S"]
goto_top = ["Home"]
goto_bottom = ["End"]
save_state_file = ["Command+S"]
