default_variable_name_type = "Unique"
default_clock_highlight_type = "Line"
snap_distance = 6
theme = ""
undo_stack_size = 50
autoreload_files = "Ask"
autoload_sibling_state_files = "Ask"
animation_time = 0.1
animation_enabled = true
max_url_length = 65534

[default_time_format]
format = "No"
show_space = true
show_unit = true

[layout]
show_hierarchy = true
show_menu = true
show_toolbar = true
show_ticks = true
show_tooltip = true
show_scope_tooltip = false
show_overview = true
show_statusbar = true
show_variable_indices = true
show_variable_direction = true
show_default_timeline = true
show_empty_scopes = false
show_hierarchy_icons = true
parameter_display_location = "Scopes"
window_width = 1920
window_height = 1080
align_names_right = false
hierarchy_style = "Separate"
waveforms_text_size = 11.0
waveforms_line_height = 16.0
waveforms_line_height_multiples = [1, 2, 4, 8, 16]
transactions_line_height = 30.0
zoom_factors = [0.5, 0.75, 0.9, 1.0, 1.1, 1.25, 1.5, 2.0, 2.5]
default_zoom_factor = 1.0
highlight_focused = true
move_focus_on_inserted_marker = true
fill_high_values = true
use_dinotrace_style = false
transition_value = "Next"

[gesture]
size = 300
deadzone = 20
background_radius = 1.35
background_gamma = 0.75

[gesture.mapping]
north = "Cancel"
south = "Cancel"
west = "ZoomIn"
east = "ZoomIn"
northeast = "ZoomOut"
northwest = "ZoomToFit"
southeast = "GoToEnd"
southwest = "GoToStart"

[behavior]
keep_during_reload = true
arrow_key_bindings = "Edge"
primary_button_drag_behavior= "Cursor"

[wcp]
autostart = false
address = "127.0.0.1:54321"

[server]
bind_address = "127.0.0.1"
port = 8911

[shortcuts]
open_file = ["Command+O"]
switch_file = ["Command+Shift+O"]
undo = ["Command+Z", "U"]
redo = ["Command+Shift+Z", "Command+Y"]
toggle_side_panel = ["B"]
toggle_toolbar = ["T"]
goto_end = ["E"]
goto_start = ["S"]
goto_top = ["Home"]
goto_bottom = ["End"]
save_state_file = ["Command+S"]
group_new = ["G"]
item_focus = ["F"]
table_view = ["L"]
select_all = ["Command+A"]
select_toggle = ["A"]
reload_waveform = ["R"]
zoom_in = ["Plus", "Equals"]
zoom_out = ["Minus"]
ui_zoom_in = ["Command+Plus"]
ui_zoom_out = ["Command+Minus"]
scroll_up = ["PageUp"]
scroll_down = ["PageDown"]
delete_selected = ["Delete", "X"]
marker_add = ["M"]
toggle_menu = ["Alt+M"]
show_command_prompt = ["Space"]
rename_item = ["F2"]
divider_add = ["D"]
