[package]
name = "surver"
version.workspace = true
edition.workspace = true
license.workspace = true
categories.workspace = true
rust-version.workspace = true
description = "Server for the Surfer waveform viewer"
repository.workspace = true

[dependencies]
bincode.workspace = true
bytesize.workspace = true
clap.workspace = true
eyre.workspace = true
lazy_static.workspace = true
leb128.workspace = true
log.workspace = true
lz4_flex.workspace = true
serde.workspace = true
serde_json.workspace = true
simple-eyre.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
web-time.workspace = true
wellen.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
fastrand = "2.3.0"
http-body-util = "0.1.2"
hyper = { version = "1.4", features = ["http1", "server"] }
hyper-util = { version = "0.1.6", features = ["tokio"] }
tokio = {workspace = true, features = ["net"]}
whoami = "1.5.1"
