# All default colors should respect a contrast ratio of at least 7:1 between
# foreground and background. Should you happen upon an exception, please report
# it as a bug on the Surfer repository.
# Using colors from the default Modus Operandi theme:
# https://github.com/protesilaos/modus-themes/blob/main/modus-operandi-theme.el
foreground = "000000" # fg-main
border_color = "9f9f9f" # border
selected_elements_colors = { background = "c4c4c4", foreground = "000000" } # bg-active, fg-main
canvas_colors = { background = "ffffff", alt_background = "f0f0f0", foreground = "000000" } # bg-main, bg-dim, fg-main
primary_ui_color = { background = "ffffff", foreground = "000000" } # bg-main, fg-main
secondary_ui_color = { background = "f0f0f0", foreground = "000000" } # bg-dim, fg-main
accent_info = { background = "a0132f", foreground = "000000" } # red-cooler, fg-main
accent_warn = { background = "d79921", foreground = "000000" } # TODO I don't know how to trigger these.
accent_error = { background = "cc241f", foreground = "000000" } # TODO
clock_highlight_line = { color = "707070", width = 2 } # bg-dim
clock_highlight_cycle = "707070" # bg-dim972500
clock_rising_marker = true
variable_default = "009900" # custom green
variable_undef = "ff0000" # custom red
variable_highimp = "ffcf00" # bg-graph-yellow-0
variable_dontcare = "0000ff" # blue-warmer
variable_weak = "303030" # custom grey
waveform_opacity = 0.5
cursor = { color="000000", width=3 } # fg-main
gesture = { color="000000", width=2 } # fg-main
linewidth = 3
alt_frequency = 0
highlight_background = "DAE8FF"

# Note: The "bg-graph-1"-variants of the bg-colors are used
# because they are lighter and thus have more contrast against
# the normal colors.
[colors]
red = "a60000"
bg-red = "ffaab4"
green = "006800"
bg-green = "8fef00"
yellow = "6f5500"
bg-yellow = "f9ff00"
blue = "0031a9"
bg-blue = "9fc6ff"
magenta = "721045"
bg-magenta = "fad0ff"
cyan = "005e8b"
bg-cyan = "afefff"
rust = "8a290f"
gold = "80601f"
olive = "56692d"
slate = "2f3f83"
indigo = "4a3a8a"
maroon = "731c52"
pink = "7b435c"

# Scope icon colors - high contrast darker colors
[scope_icons.colors]
module = "0031a9"
task = "8a290f"
function = "721045"
begin = "006800"
fork = "a60000"
generate = "0031a9"
struct = "005e8b"
union = "005e8b"
class = "731c52"
interface = "56692d"
package = "80601f"
program = "6f5500"
vhdl_architecture = "0031a9"
vhdl_procedure = "8a290f"
vhdl_function = "721045"
vhdl_record = "005e8b"
vhdl_process = "006800"
vhdl_block = "2f3f83"
vhdl_for_generate = "0031a9"
vhdl_if_generate = "0031a9"
vhdl_generate = "0031a9"
vhdl_package = "80601f"
ghw_generic = "2f3f83"
vhdl_array = "4a3a8a"
unknown = "303030"

# Variable icon colors - high contrast darker colors
[variable_icons.colors]
wire = "006800"
bus = "0031a9"
string = "8a290f"
event = "731c52"
other = "721045"

[ticks]
style = { color="9f9f9f", width=2 }
density = 1
